name: Season
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+10

environment:
  sdk: ^3.3.1

dependencies:
  flutter:
    sdk: flutter
  email_validator: ^3.0.0
  validators: ^3.0.0
  form_field_validator: ^1.1.0
  shared_preferences: ^2.0.18

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  http: ^1.2.2
  syncfusion_flutter_calendar: ^23.1.43
  # multi_image_picker2: ^5.0.1
  # image_picker: ^0.8.4+1
  select_form_field: ^2.2.0
  datetime_picker_formfield: ^2.0.1
  equatable: ^2.0.5
  marquee: ^2.2.3
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  mime: ^1.0.4
  dio: ^5.0.1
  circular_bottom_navigation: ^2.3.0
  url_launcher: ^6.1.10
  link_text: ^0.2.0
  flutter_launcher_icons: ^0.14.1
  widget_permission_manager: ^2.0.2
  open_file: ^3.2.1
  path_provider: ^2.0.13
  expansion_tile_card: ^3.0.0
  background_fetch: ^1.1.5
  syncfusion_flutter_pdfviewer: ^23.1.43
  #flutter_local_notifications: ^8.2.0
  easy_image_viewer: ^1.2.1
  flutter_pdfview: ^1.3.1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/season-intranet.png
    - assets/icons/season-intranet.png
    - assets/images/avatar.png
    - assets/images/kind.png
    - assets/images/double.png
    - assets/images/simple.png
    - assets/agent_booklet.pdf
    - packages/timezone/data/latest.tzf
    - assets/agent_booklet.pdf
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Light.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
